# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
  - name: Package installation
    init: >
      sudo apt install gfortran curl
      curl -sSL https://raw.githubusercontent.com/pdm-project/pdm/main/install-pdm.py | python3 -
      export PATH=/workspace/.pyenv_mirror/user/current/bin:$PATH
      