image: python:3.8-bullseye

stages:
  - test
  - deploy
  - release

variables:
  GIT_DEPTH: 0
  GIT_STRATEGY: clone

test:
  stage: test
  script:
    - apt-get update --allow-releaseinfo-change
    - apt-get install -yqq --no-install-recommends graphviz cmake gfortran gcc g++ make curl
    - python3 --version
    - pip3 install pdm
    - echo ${CI_COMMIT_TAG:-"0.0.0.dev+$CI_COMMIT_SHORT_SHA"}
    - PDM_BUILD_SCM_VERSION=${CI_COMMIT_TAG:-"0.0.0.dev+$CI_COMMIT_SHORT_SHA"} pdm install
    - PDM_BUILD_SCM_VERSION=${CI_COMMIT_TAG:-"0.0.0.dev+$CI_COMMIT_SHORT_SHA"} pdm run pytest
    - PDM_BUILD_SCM_VERSION=${CI_COMMIT_TAG:-"0.0.0.dev+$CI_COMMIT_SHORT_SHA"} pdm doc
  artifacts:
    when: always
    paths:
      - build/htmldoc

# https://ydethe.gitlab.io/pikendus-backend/htmldoc/pikendus-backend/
pages:
  stage: deploy
  dependencies:
  - test
  script:
    - cp -r build/htmldoc public
  artifacts:
    paths:
      - public

package:
  stage: deploy
  dependencies:
  - test
  script:
    - apt-get update --allow-releaseinfo-change && apt-get install -yqq --no-install-recommends python3-pip
    - pip3 install pdm
    - pdm config --global repository.gitlab.url ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi
    - pdm config --global repository.gitlab.username gitlab-ci-token
    - pdm config --global repository.gitlab.password ${CI_JOB_TOKEN}
    - PDM_BUILD_SCM_VERSION=${CI_COMMIT_TAG:-"0.0.0.dev+$CI_COMMIT_SHORT_SHA"} pdm build
    - pdm publish -r gitlab
  only:
    - tags
    - master
