image: python:3.8-bullseye

stages:
  - test
  - deploy
  - release

test:
  stage: test
  script:
    - apt-get update --allow-releaseinfo-change
    - apt-get install -yqq --no-install-recommends graphviz cmake gfortran gcc g++ make curl
    - python3 --version
    - curl -sSL https://raw.githubusercontent.com/pdm-project/pdm/main/install-pdm.py | python3 -
    - export PATH=/root/.local/bin:$PATH
    - pdm install
    - pdm build
    - pdm run pytest
    - pdm doc
  artifacts:
    when: always
    paths:
      - htmldoc

# https://ydethe.gitlab.io/pikendus-backend/htmldoc/pikendus-backend/
pages:
  stage: deploy
  dependencies:
  - test
  script:
    - cp -r htmldoc public
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'

package:
  stage: deploy
  dependencies:
  - test
  rules:
    - if: $CI_COMMIT_TAG =~ /^v(?:\d+.){2}(?:\d+)$/
      when: always
  script:
    - apt-get update --allow-releaseinfo-change
    - apt-get install -yqq --no-install-recommends git python3-venv curl
    - curl -sSL https://raw.githubusercontent.com/pdm-project/pdm/main/install-pdm.py | python3 -
    - export PATH=/root/.local/bin:$PATH
    - pdm config repository.pypi.url https://upload.pypi.org/legacy/
    - pdm config repository.pypi.username __token__
    - pdm config repository.pypi.password ${PYPI_TOKEN}
    - pdm publish

