repos:
- hooks:
  - id: check-changelog
    args: [--version-regex, '<a href="[^"]+">(?P<version>[^<]+)', --bump-latest]
  repo: https://gitlab.com/ydethe/pdm-copier.git
  rev: v0.4.0

- repo: local
    hooks:
      # Prevent committing .rej files
      - id: forbidden-files
        name: forbidden files
        entry: found Copier update rejection files; review them and remove them
        language: fail
        files: "\\.rej$"

  # Some "common" checks useful for almost any repo
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      #- id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-yaml
      - id: mixed-line-ending
      - id: trailing-whitespace

  # Automatically format Python code
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        additional_dependencies: ["click==8.0.4"]
        args: ["-l", "100", "--force-exclude", "kt_.*.py"]

  - repo: https://github.com/adamchainz/blacken-docs
    rev: v1.12.1
    hooks:
      - id: blacken-docs
        additional_dependencies:
          - black==22.3.0
          - click==8.0.4
        args: ["-l", "100"]

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    # Ruff version.
    rev: v0.0.261
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
