site_name: pikendus backend
repo_url: https://gitlab.com/ydethe/pikendus-backend
theme:
  name: material
nav:
  - Home: "index.md"
  - Changelog: "CHANGELOG.md"
plugins:
  - include-markdown
  - search
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
